apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  namespace: tenant-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: hashicorp/http-echo
        args:
        - "-text=Hello from Reviews v1"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  namespace: tenant-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
      - name: reviews
        image: hashicorp/http-echo
        args:
        - "-text=Hello from Reviews v2"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-v1
  namespace: tenant-a
spec:
  selector:
    app: reviews
    version: v1
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-v2
  namespace: tenant-a
spec:
  selector:
    app: reviews
    version: v2
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: reviews-route
  namespace: tenant-a
spec:
  parentRefs:
  - name: shared-gateway
    namespace: gateway-system
  hostnames:
  - reviews.example.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: reviews-v1
      port: 8080
      weight: 80
    - name: reviews-v2
      port: 8080
      weight: 20