apiVersion: v1
kind: Namespace
metadata:
  name: tenant-b
  labels:
    tenant: tenant-b
---
apiVersion: v1
kind: Service
metadata:
  name: serverb-service
  namespace: tenant-b
spec:
  selector:
    app: serverb
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverb
  namespace: tenant-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serverb
  template:
    metadata:
      labels:
        app: serverb
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo
        args: ["-text=Hello from ServerB"]
        ports:
        - containerPort: 8080
